image: ncrmro/ci-compose

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - auto-selenium

auto-selenium:
  stage: auto-selenium
  cache:
    paths:
    - node_modules/
  before_script:
#   - yarn install
   - yarn run d:test:selenium pull
   - yarn run d:build
   - yarn run d:test:up
   - ls
   - ls ./__tests__
   - yarn run d:test:compile
   - ls ./__tests__
  script:
   - yarn run d:test