variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  
build:
  stage: build
  image: node:latest
  cache:
    paths:
    - node_modules/
  before_script:
   - ls ./
  script:
   - yarn install
   - yarn run build