version: '3.4'
services:
  auto-selenium:
    image: ncrmro/auto-selenium
    depends_on:
      - selenium_hub
      - client-server
    volumes:
       - ./__tests__:/app/__tests__
       - ./screenshots:/app/screenshots
    environment:
      SELENIUM_URL: selenium_hub:4444
      CLIENT_SERVER_URL: client-serve:5000

  firefox:
    image: selenium/node-firefox-debug:3.9.1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    environment:
      HUB_HOST: selenium_hub
    ports:
      - "5901:5900"

  chrome:
    image: selenium/node-chrome-debug:3.9.1
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium_hub
    environment:
      HUB_HOST: selenium_hub
    ports:
      - "5900:5900"

  selenium_hub:
    image: selenium/hub:3.9.1
    hostname: selenium_hub
    ports:
      - "4444:4444"
